name: emplaca_ai
description: "A cross-platform vehicle and driver tracking application built with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0

  # Security & Authentication
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3
  local_auth: ^2.1.6

  # State Management
  provider: ^6.0.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # PDF Generation
  pdf: ^3.10.4

  # File & Path Management
  path_provider: ^2.1.0
  share_plus: ^7.1.0

  # Utilities
  intl: ^0.18.1
  uuid: ^3.0.7

  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Analysis & Linting
  flutter_lints: ^2.0.0

  # Hive Code Generation
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic