// lib/domain/usecases/vehicle/add_vehicle.dart

import '../../entities/vehicle.dart';
import '../../repositories/vehicle_repository.dart';
import '../../../core/errors/exceptions.dart';
import '../../../core/utils/validators.dart';

/// Use case for adding a new vehicle
/// Validates input data and delegates to repository
class AddVehicle {
  final VehicleRepository _repository;

  AddVehicle(this._repository);

  /// Adds a new vehicle with validation
  Future<Vehicle> call({
    required String licensePlate,
    required String model,
    required String brand,
    required String userId,
    bool isActive = true,
  }) async {
    // Validate inputs
    _validateInputs(
      licensePlate: licensePlate,
      model: model,
      brand: brand,
      userId: userId,
    );

    // Create vehicle entity
    final vehicle = Vehicle(
      id: '', // Will be generated by repository
      licensePlate: licensePlate.toUpperCase().trim(),
      model: model.trim(),
      brand: brand.trim(),
      isActive: isActive,
      createdAt: DateTime.now(),
      userId: userId,
    );

    // Add vehicle through repository
    return await _repository.addVehicle(vehicle);
  }

  /// Validates all input parameters
  void _validateInputs({
    required String licensePlate,
    required String model,
    required String brand,
    required String userId,
  }) {
    final errors = <String>[];

    // Validate license plate
    if (licensePlate.trim().isEmpty) {
      errors.add('Placa é obrigatória');
    } else if (!Validators.isValidBrazilianLicensePlate(licensePlate.trim())) {
      errors.add('Formato de placa inválido (use ABC1234 ou ABC1D23)');
    }

    // Validate model
    if (model.trim().isEmpty) {
      errors.add('Modelo é obrigatório');
    } else if (model.trim().length < 2) {
      errors.add('Modelo deve ter pelo menos 2 caracteres');
    } else if (model.trim().length > 50) {
      errors.add('Modelo deve ter no máximo 50 caracteres');
    }

    // Validate brand
    if (brand.trim().isEmpty) {
      errors.add('Marca é obrigatória');
    } else if (brand.trim().length < 2) {
      errors.add('Marca deve ter pelo menos 2 caracteres');
    } else if (brand.trim().length > 30) {
      errors.add('Marca deve ter no máximo 30 caracteres');
    }

    // Validate user ID
    if (userId.trim().isEmpty) {
      errors.add('ID do usuário é obrigatório');
    }

    // Throw validation exception if there are errors
    if (errors.isNotEmpty) {
      throw ValidationException(errors.join(', '));
    }
  }
}
